ares.components += mos6502

ares.objects += ares-apple1-system
ares.objects += ares-apple1-controller
ares.objects += ares-apple1-cartridge
ares.objects += ares-apple1-cpu
ares.objects += ares-apple1-vdp

$(object.path)/ares-apple1-system.o:     	$(ares.path)/apple1/system/system.cpp
$(object.path)/ares-apple1-controller.o: 	$(ares.path)/apple1/controller/controller.cpp
$(object.path)/ares-apple1-cartridge.o:  	$(ares.path)/apple1/cartridge/cartridge.cpp
$(object.path)/ares-apple1-cpu.o:     		$(ares.path)/apple1/cpu/cpu.cpp
$(object.path)/ares-apple1-vdp.o:     		$(ares.path)/apple1/vdp/vdp.cpp
