ares.components += z80
ares.components += tms9918
ares.components += ay38910

ares.objects += ares-bbcbc-cpu
ares.objects += ares-bbcbc-vdp
ares.objects += ares-bbcbc-psg
ares.objects += ares-bbcbc-system
ares.objects += ares-bbcbc-cartridge

$(object.path)/ares-bbcbc-cpu.o:        $(ares.path)/bbcbc/cpu/cpu.cpp
$(object.path)/ares-bbcbc-vdp.o:        $(ares.path)/bbcbc/vdp/vdp.cpp
$(object.path)/ares-bbcbc-psg.o:        $(ares.path)/bbcbc/psg/psg.cpp
$(object.path)/ares-bbcbc-system.o:     $(ares.path)/bbcbc/system/system.cpp
$(object.path)/ares-bbcbc-cartridge.o:  $(ares.path)/bbcbc/cartridge/cartridge.cpp
